### ISSUE TITLE
Error deleting zimbra distribution list

### ISSUE THREAD

**Issue by cainelli** [inova-tecnologias/jenova#18]
```
[2016-09-13 14:48:50,014] ERROR in app: Exception on /services/zimbra/domains/domain.com.br/dlists/test@domain.com.br [DELETE]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/jenova/resources/base.py", line 65, in decorated
    return f(*args, **kwargs)
  File "/opt/jenova/resources/distribution_list.py", line 262, in delete
    Zr.deleteDistributionList(dlist_zimbra_id = zid)
NameError: global name 'Zr' is not defined
```

**Comment by cainelli** [comment]
fixed
